language: python
sudo: false
branches:
only:
  - master

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - pip install -U pip
  - pip install git+git://github.com/carsonfarmer/addc.git

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - py.test addc --cov addc -v --cov-report term-missing

notifications:
    email:
        recipients:
            - carsonfarmer@gmail.com
        on_success: always
        on_failure: always

after_success:
  - coveralls
